# Setup
title:               Seungtae's blog
tagline:             'CV/ML'
description:         'This is my personal blog.'
url:                 https://stnamjef.github.io
baseurl:             ''
paginate:            1
permalink:           pretty

Disqus-shortname:    stnamjef-github-io

# About/contact
author:
  name:              Seungtae
  contact:
    github:            https://github.com/stnamjef
    email:             mailto:stnamjef@naver.com

# Gems
# plugins:
#   - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
